### ISSUE TITLE
Control package dependencies based on tracks being used

### ISSUE THREAD

**Issue by heimannch** [paul-shannon/igvShiny#10]
I am using igvShiny in my app and I've notice that it is demanding a lot of memory.
My application uses the following tracks:
- RefSeq
- Gencode
- GWAS

I imagine that some of the current package dependencies are not necessary for these tracks - would it be possible to control the dependencies based on the widget resources being used?

Thanks!

**Comment by paul-shannon** [comment]
Hi @heimannch,   Starting on this now, finally.  I will keep you apprised.
Do you still want to specify various colors for the GWAS track?

**Comment by paul-shannon** [comment]
@heimannch, Carolina -  inst/demos/igvShinyDemo,.R with MotifDb and VariantAnnotation packages removed, deploys to run in the "Large" memory model, needing just over 600M.  Is that an improvement over what you have seen?    Version 1.2.13 of the package.

**Comment by heimannch** [comment]
Hi @paul-shannon, thanks for taking a look at this! I will test the new version and report how it goes.

About the GWAS track: I am planning on opening an issue with some suggestions and questions that I had during my initial attempts of implementing it in my shiny app. I had to pause this for a while - we will need to have a working version of the app more than a month earlier than anticipated, so some rearrangement of activities was necessary - but I can open this issue now, if it is more convenient for you.

**Comment by paul-shannon** [comment]
Hi @heimannch,  either now or later, you be the judge.   Maybe more important is for me to provide rapid fixes or features you need for the upcoming release.  Glad to do that!

**Comment by heimannch** [comment]
@paul-shannon, I successfully deployed my shiny app in a large instance size (instead of a xlarge) with the version 1.2.14 of igvShiny.  Thanks!

**Comment by paul-shannon** [comment]
resolved
