### ISSUE TITLE
Support for custom genomes

### ISSUE THREAD

**Issue by bknightATSSU** [paul-shannon/igvShiny#20]
Hi, I've been working on implementing IGV in a Shiny app and started with using igvShiny, but I've moved to trying your other package igvR because of its `setCustomGenome` function. We'd like to use igvShiny instead because of its integration with Shiny, but we need it for other genomes that aren't supported. We saw [this request](https://github.com/paul-shannon/igvR/issues/6) and were wondering if it would be possible to implement something like `setCustomGenome` in igvShiny. Thanks!

**Comment by paul-shannon** [comment]
Hi Bridget,

It ought to be quite straightforward - since both packages depend on Jim Robinson’s igv.js to do all the hard work.

Maybe you would be available to help?   

 - Paul

**Comment by bknightATSSU** [comment]
Hi, thanks for the quick response!

Yes, I can definitely help. I'll create a fork and start implementing it. 

Bridget

**Comment by ChristianRohde** [comment]
Hi, was there a way to make setCustomGenome work with igvShiny? A while ago I created a custom igv ".genome" file for a short stretch of ribosomal DNA using this method (https://software.broadinstitute.org/software/igv/iPadUserGenomes => at the moment I have no access to this page?!). I still can use this file with my igv software via "Genomes/Load Genome from File". It would be cool if there is a way to use such file in igvShiny

**Comment by paul-shannon** [comment]
@ChristianRohde - should be possible, could probably add it within a week.  Can you provide your custom genome for me to use (fasta and GFF3)?

**Comment by ChristianRohde** [comment]
nice, I used this source: https://www.ncbi.nlm.nih.gov/nuccore/555853 and just exported fasta and gff3 there.  

[nuccore_555853_fasta_gff3.zip](https://github.com/paul-shannon/igvShiny/files/8290186/nuccore_555853_fasta_gff3.zip)

**Comment by paul-shannon** [comment]
@ChristianRohde - sorry for the delay, I had a talk to prepare.   Are you still interested in custom genome support?  If so, I will get to work on it today.

**Comment by ChristianRohde** [comment]
Hi @paul-shannon I would still use this feature to display our data mapped to to a custom rRNA or tRNA genome. At the moment I need to use the IGV installation on a lokal PC. This works, but with igvShiny it would be much easier to quickly load these data on demand.

**Comment by paul-shannon** [comment]
@ChristianRohde - a quick update.   I have created a new branch, "customGenome" and I'm doing some refactoring.

In my current thinking, the first argument to the igvShiny - rather than an options list - is a genomeSpec list, which can be as simple as ```list(genomeCode="hg38")``` or as complex as 
```
list(genomeCode="custom",
     fasta="https://xxx.fa",  # or a local filename
     fasta.index="https://xxx.fai",  # or a local filename
     geneone.annotation="https://zzz.gff3" # or a local filename
     ) 
```
The constructor will test the validity of the genomeSpec, and the accessibility of the local or remote files (if any).

What do you think?

**Comment by paul-shannon** [comment]
gff3 can be optional, sure!  

Would you ever want to handcraft annotation along your genome, in a simpler format?

**Comment by ChristianRohde** [comment]
Hi @paul-shannon, can I already use the branch you created? I installed it on my laptop via remotes::install_github("paul-shannon/igvShiny", ref = "customGenome"), but I did not figure out how I can launch it with renderIgvShiny myself. So far I only get errors. Best, Christian

**Comment by ChristianRohde** [comment]
Hi @paul-shannon,  thank you for your quick response but please do not hurry. I thought that maybe I misunderstood your message and I should have tested some time ago and you are waiting for a feedback from my side...

**Comment by paul-shannon** [comment]
@ChristianRohde This is ready for you now to test.   Some details:

1. do a fresh pull on this repo
2. switch to the ```customGenome``` branch
3. install the package
4. run each of the very small shinyApps in ```inst/demos/customGenomes```
5. ``` customGenome-localFiles-sars.R``` uses fasta, fai, and gff3 for Sars-CoV-2, all local files
6. ``` customGenome-remoteFiles-sars.R``` uses fasta, fai, and gff3 for Sars-CoV-2, all files read by http, from my publicly visible webserver
The principal innovation here is that the package has a new function ```parseAndValidateGenomeSpec```.  The validated list is that passed to igvShiny, all files (both local and remote) tested so we know they can be read.

After those two simple shiny apps run fine for you, and you understand how to make your own genomeSpec, please try your own data and let me know how it goes.

**Comment by ChristianRohde** [comment]
Hi @paul-shannon, both of your examples work well. I can also load & run my custom genome from local files such as data.directory <- normalizePath("~/Documents/rRNA_genome/"). Next I learned how to limit the gff3 file to make it show the content I want to annotate only:
<img width="849" alt="Screenshot 2022-05-08 at 22 57 14" src="https://user-images.githubusercontent.com/63801549/167315808-c5ca25ae-75a5-4967-98f5-19ed095cac38.png">

Looks like it works well so far. Thank you very much!

**Comment by paul-shannon** [comment]
this issue now resolved with the merge of the customGenomes branch into master.
