### ISSUE TITLE
When igvShiny set genomeName to remote or local, it can add Annotation track?

### ISSUE THREAD

**Issue by chikao0817** [paul-shannon/igvShiny#23]
Hi Paul,

Thank you very much for developing this wonderful package to browse genome in R Shiny.
I have some questions about when set genomeName for "remote" or "local" in igvShiny( ) for custom genome.

Is any function like loadVcfTrack such as "loadAnnotationTrack" to loading Annotation track from gtf/gff3 or rtracklayer object?
It will be helpful for custom genome setting in igvShiny.

![image](https://user-images.githubusercontent.com/47777206/155682039-049d025f-2d9c-4c7e-a2d0-b80d8bb04142.png)

Another question is genomeName, it will change to "remote" mabye it can be a setting genome id like igvR setCustomGenome?

Best,
     Chi Kao

**Comment by paul-shannon** [comment]
@chikao0817  I'll be glad to assist with this.  Your situation may be faced by others as well, so I could document the steps needed.   
A good place to start is for me to get a good grasp of your goals.   And then together we create a minimal  data set - usually the smaller the better, as long as it captures the complexity you face.  

Can you put your shiny app on github?

**Comment by chikao0817** [comment]
@paul-shannon
Thank you for the prompt reply :)

It is a small example shiny with custom genome.
https://github.com/chikao0817/customgenome_shiny

local fasta and annotation file (gff3) are subset partial from ENSEMBL.
https://fungi.ensembl.org/Serendipita_indica_dsm_11827_gca_000313545/Info/Index

If I want add track file from rtraklayer or directly by gff3 for initial igvShiny() ?
How can I add result like hg19 gene tracks looks like?
![image](https://user-images.githubusercontent.com/47777206/156101736-8b9ee617-b737-4e1b-858f-f034707575d9.png)

Another issue when I load local fasta it will show warning. 
![image](https://user-images.githubusercontent.com/47777206/156101264-1b2a14be-ae3a-4dc2-8a3b-69072075f22c.png)

Sorry, I am only familiar with R program
It still show igv genome fine, why javascript warn like that?

Best,
Chi Kao

**Comment by paul-shannon** [comment]
@chikao0817 Chi Kao,  I am working on this now, fitting it in among other tasks, should have a fix for you in a few days.  Thanks for the report!

**Comment by chikao0817** [comment]
@paul-shannon Hi Paul,

Thanks a lot for developing new version of igvShiny.
I look forward to using custom genome more flexibility in future version :)

Best,
Chi Kao

**Comment by paul-shannon** [comment]
@chikao0817 Hi Chi Kao,
I have this mostly worked out now but will be delayed till next week before I have it ready.  Sorry for the delay - and thanks for making the request.

**Comment by paul-shannon** [comment]
@chikao0817  -
Annotation (gff3) tracks are now supported.  See i```nst/demos/igvShinyDemo-GFF3.R```
Is this what you were looking for?   I hope so!
![image](https://user-images.githubusercontent.com/2480712/158676654-e895a0f9-5214-4510-abe9-34dfa70046ba.png)

**Comment by chikao0817** [comment]
@paul-shannon 

Thanks for quickly and wonderful updated, it makes using custom genome more flexible.
Yes, this is my hope, and color attribute is exellent!

A little question about Demo.
I found in inst/demos/igvShinyDemo-GFF3.R
local file GRCh38.94.NDUFS2.gff3 not in exdata. Maybe just forget to upload?

-------------
Another issue when I load local fasta it still show this warning. (Open a new issue?)
![image](https://user-images.githubusercontent.com/47777206/158965605-5e7d065a-9f8e-41c0-b77e-c6ead6942553.png)

And ~500 Mb genome loading a while time (~10 min).
Any suggestion for custom local genome loading speed up 
like upload a fasta and fai file in [igv app](https://igv.org/app/)?

Is some way loading genome like using ScanBamParam to read subset bam in visual region 
and it loading time is good?
![image](https://user-images.githubusercontent.com/47777206/158981557-7cb7adea-63cc-48ed-9e5f-837bcc9096d0.png)

Also the file for genome is large, so I upload app example in [google dirve](https://drive.google.com/drive/folders/1EXeH4a202CU43Xhgxbvn_wv25NwWWcbM?usp=sharing)

When I use igvShiny, it will save many tmp.bam and gff3 file in tracks.
How could I clean this file after close session automaticly?

In my using experience, igvShiny is the best package for interactive genome viewer in R Shiny.
I hope this package will be known for more Shiny app developer :)

Thanks a lot.

**Comment by paul-shannon** [comment]
@chikao0817 I am closing this issue, opening a new one to address your question:

 ```When I use igvShiny, it will save many tmp.bam and gff3 file in tracks.
How could I clean this file after close session automatically?```
