### ISSUE TITLE
Load large local fasta file size, igvShiny will not show any base information?

### ISSUE THREAD

**Issue by chikao0817** [paul-shannon/igvShiny#24]
@paul-shannon 

Hi Paul,

Thanks a lot for adding gff3 track develop. It was very useful 😊 .

But I found some issue about load local fasta file in igvShiny.
Maybe this bug or limit is about igv.js load local fasta from server.

I test two local fasta genome from ENSEMBL PLANT database and Solgenomic Network for igvShiny.
First, the Solanum lycopersicum genome. 
S_lycopersicum_chromosomes.3.00.fa file size is around 803 Mb.
Second, the Oryza sativa genome. 
Oryza_sativa.IRGSP-1.0.dna.toplevel.fa file size is around 364 Mb.

When app run in Rstudio local apps (127.0.0.1:4094)
Both two genome can show base information like figure.

![igvShiny_localfasta_issue](https://user-images.githubusercontent.com/47777206/160335125-d686303e-2612-49e6-a6ae-9c589e738d24.png)

Loading much time and before loading base information
show **WARNING: range-byte header was ignored for url** info like issue.
#23 

But when app run in rstudio-server in local server (192.168.100.6:3838)
Oryza sativa genome works fine, but  Solanum lycopersicum genome didn't jump warning message
and also can't show base information like figure.
![igvShiny_localfasta_issue2](https://user-images.githubusercontent.com/47777206/160335053-1857c45d-eb4c-4160-891f-c8da64f61b1b.png)

I guess this maybe a local file size issue for igvShiny base on igv.js.
Additionally, issue about **range-byte header was ignored for url** in igv.js happend in some local file upload.
https://github.com/igvteam/igv.js/issues/680
https://github.com/igvteam/igv.js/issues/1049

When I upload  Solanum lycopersicum local fasta to IGV App
It didn't jump  **range-byte header was ignored for url** and base information looks great.
Is about different version for igv.js? or java version? for local url.
![image](https://user-images.githubusercontent.com/47777206/160049632-efcf5c7e-b00a-4799-a2c3-40620c38ded6.png)

I also upload this two genome fasta and fai in [gdrive](https://drive.google.com/drive/folders/1EXeH4a202CU43Xhgxbvn_wv25NwWWcbM).

Hope this issue will help.

Best regards,
Kao Chi

**Comment by paul-shannon** [comment]
@chikao0817  Thank you for this bug report, and sorry for my slow response.
I am spending the next week preparing for a talk, so I cannot look into these things till the week after.
Please understand that 1) your report is very valuable, and much appreciation and 2) that I will try to get everything fixed by  april 8th.

**Comment by paul-shannon** [comment]
@chikao0817   What webserver do you use to serve up your rice and tomato genomes?
I used to depend on python flask, but recurring recent problems led me to shift to nginx, cors and byte-range enabled.
I see the warning "range-byte header ignored" - that tells me that igv.js had to load the entire genome, which would explain very slow load times.   

Tell me the details, please, of your webserver?

**Comment by chikao0817** [comment]
@paul-shannon 

Thank you for all your assistance, I really appreciate your help for resolving this issue.

Sorry for my slow respone about my app webserver setting,  I prepare a file sets which is a small set shiny app  with two genome (rice and tomato) and shinyproxy in [gdrive](https://drive.google.com/drive/folders/1EXeH4a202CU43Xhgxbvn_wv25NwWWcbM) which as mentioned above.

I use [shinyproxy ](https://github.com/openanalytics/shinyproxy) to manage users and shiny apps.
application.yaml for this proxy setting, and use DockerFile in directory to build shinyproxy docker image.
`docker build -t shinyproxy [shinyproxy_dirpath]`
Please notice that application.yaml specs: , container-volumes **apppath** may edit for the realpath for docker volume.


Then create a bridge docker network shinyproxy-net, for shiny docker and shinyproxy interaction
`docker network create shinyproxy-net`

Besides, dockerize igvShiny_TestApp for DockerFile in directory.
To install R packages and BSgenome for rice and tomato genome., it will take a while to build docker image.
`docker build -t igvshiny_test [igvShiny_Test_dirpath]`

After docker image prepare, excute shinyproxy and assign port 8080 to webserver
`docker run -d -v /var/run/docker.sock:/var/run/docker.sock --net shinyproxy-net -p 8080:8080 shinyproxy`

I use nginx for the webserver, linux os system is CentOS Stream 8, and nginx version is 1.14.1
Also I put my nginx.conf in gdrive, and edit the server name to example.com.

After login shinyproxy (account : igvShinyTest   ;  password : igvShinyTest) which is setting in application.yaml.
You can try igvShiny_Test app，click genome DT to select and  check genome to next page.
![image](https://user-images.githubusercontent.com/47777206/160334166-8d61390d-90f3-490b-9029-e9a10fea6583.png)
![image](https://user-images.githubusercontent.com/47777206/160334203-6a71ee48-767b-473a-96b8-a90f45d4f038.png)


Thanks a lot for this issue discussion.

Best regards,
Kao Chi

**Comment by paul-shannon** [comment]
I suggest you isolate the problem, using the clue I proposed last time:

You need to host your genome files in a stand-alone cors/byte-range webserver.  Then test that completely separately from your shiny app.  Look into the command line tool “curl” and how to make cors and byte-range requests from the command line.  

Let me know once that is working.  Then I can reproduce your subsequnt problems from my laptop.

 - Paul

**Comment by chikao0817** [comment]
@paul-shannon 

Thanks the clue about byte-range webserver. I search some issue in nginx byte-range webserver setting.
And find this post, and ngx http proxy module setting.

https://stackoverflow.com/questions/22728016/nginx-is-not-accepting-range-of-bytes
http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_force_ranges

When I setting nginx.conf for **proxy_force_ranges on;** 
and restrat nginx server

The App works great and speed up !!
![image](https://user-images.githubusercontent.com/47777206/160447705-3831b63b-730f-4808-9311-6e194754f4f0.png)

I think I ask a stupid question because I don't know what is byte-range request : P

Additionally, I find if  `loadGFF3TrackFromLocalData`
colorByAttribute (biotype) not set in color.table list , it will random assign color ?

Thank you for your kind cooperation.

Best regards,
Kao Chi

**Comment by paul-shannon** [comment]
@chikao0817 - please open a new separate issue on your gff3 track question.  I will then take a look.   For now, I will close this "large local fasta file" issue.
