### ISSUE TITLE
Unexpected interaction between igvShiny and cyjShiny

### ISSUE THREAD

**Issue by heimannch** [paul-shannon/igvShiny#27]
Hi Paul,

I've found a weird issue that I'm not even sure is an igvShiny issue, but since it seems that some sort of interaction is happening with this package and cyjShiny, I thought you might have some idea of what is going on here.

Steps to reproduce the issue: 
1. Access https://isb-cgc.shinyapps.io/iatlas-testing/
2. In the left menu, access "Cell-Interaction Diagram". You'll see on the right panel a network that uses cyjShiny
3. In the left menu, access "Germline Analysis". The second section (GWAS) was supposed to show an IGV plot, but it's not there.

If you restart the app and switch steps 2 and 3, you'll see the IGV plot, but not the cyjShiny network. I tried removing the animation from `shinycssloaders::withSpinner(.)` as the javascript console showed some tags that I believe are associated with that, but the problem persists.

**Comment by paul-shannon** [comment]
Hi Carol,  I have taken a look and have no clue!  All I can think of is something which you will have thought of yourself, or which may be impractical.
Which is to create a mode for your igvShiny & cyjShiny widgets (some presumed wrapper around my work) such that a simple message display is rendered.  Something like a div with static text
```
I am a dummy igvShiny widget, pretending to display chrN:x-y of hg19
```
I realize I am not being much help here.

**Comment by heimannch** [comment]
Thanks for taking a look at this, Paul! 
I don't understand exactly your suggestion and how it could help solve/troubleshoot this issue, but would be glad to give it a try.

And I forgot to mention: in the sequence of steps in my initial comment, the IGV plot doesn't appear, but I can see in the console all the messages associated with the creation of the track file - so if I understand correctly, the plot is built but not displayed.

**Comment by paul-shannon** [comment]
I’ll try to do a better job of explaining my idea.

Imagine that you have an igvShiny object - an instance of a class that contains all the details needed to create and run an actual igv.js in a specified div, connected to R in the way that the htmlwidgets package allows us to do.  Call it ```igvShinyWrapperClass```.

```
igv <- igvShinyWrapperClass(enclosingDiv, initialLocus="NDUFS2", genome="hg38",
                   mode="fullOperational")
```
You can construct and insert and make calls to this in your big webapp.
Then when problems arise, you could try a few things:
```
igv <- igvShinyWrapperClass(enclosingDiv, initialLocus="NDUFS2", genome="hg38",
                   mode="dummyMode")
```
And then test:  does the dummy igvShinyWrapper instance display properly in your webapp?
Depending on the answer, you could test further:   

- does the fully operational instance display in a minimal single panel shiny app?
- when mixed with a similarly wrapped  cyjShiny?
- how do the the "dummyMode" instances behave?  Can you reproduce the problem using just them?

I find it very difficult to debug problems in the middle of a big program.  So I try to reproduce the problem in the minimal circumstances, where fewer things are happening, and I have a chance to see all the moving parts.

Does this help?  I am explaining the obvious? :)

**Comment by heimannch** [comment]
Oh yes, it makes a lot of sense, and it made me feel the need to build a prototype from scratch to see which new code addition introduced the error. It didn't take long to be able to have a small reproducible example (an adaptation of igvShinyDemo-withModules.R, uses file in this directory).

```
library(shiny)
library(igvShiny)
library(cyjShiny)
library(GenomicAlignments)

#cyjshiny object

tbl.nodes <- data.frame(id=c("A", "B", "C"),
                        type=c("kinase", "TF", "glycoprotein"),
                        lfc=c(-3, 1, 1),
                        count=c(0, 0, 0),
                        stringsAsFactors=FALSE)

tbl.edges <- data.frame(source=c("A", "B", "C"),
                        target=c("B", "C", "A"),
                        interaction=c("phosphorylates", "synthetic lethal", "unknown"),
                        stringsAsFactors=FALSE)

graph.json <- toJSON(dataFramesToJSON(tbl.edges, tbl.nodes), auto_unbox=TRUE)

#----------------------------------------------------------------------------------------------------
f <- system.file(package="igvShiny", "extdata", "gwas.RData")
stopifnot(file.exists(f))
tbl.gwas <- get(load(f))
print(dim(tbl.gwas))
printf <- function(...) print(noquote(sprintf(...)))
ns.sep <- "."
#----------------------------------------------------------------------------------------------------
igv_ui = function(id){

  ns <- NS(id)

  shinyUI(fluidPage(
        igvShinyOutput(ns('igvShiny_0')),
        cyjShiny::cyjShinyOutput(ns('cyjShiny')),
        width=10
  )
  )
}
#----------------------------------------------------------------------------------------------------
igv_server <-  function(input, output, session) {

   ns <- session$ns

   genomes <- c("hg38", "hg19", "mm10", "tair10", "rhos")
   loci <- c("chr5:88,466,402-89,135,305", "MEF2C", "Mef2c", "1:7,432,931-7,440,395", "NC_007494.2:370,757-378,078")
   i <- 2

   output$igvShiny_0 <- renderIgvShiny(
     igvShiny(list(
        genomeName=genomes[i],
        initialLocus=loci[i],
        displayMode="SQUISHED"
        ))
      )

   output$cyjShiny <- cyjShiny::renderCyjShiny({
     cyjShiny::cyjShiny(graph=graph.json, layoutName="cola")
   })

} # server
#----------------------------------------------------------------------------------------------------

server <- function(input, output, session){
  callModule(igv_server, "igv")
}

ui <- fluidPage(
  igv_ui(id="igv")
)

runApp(shinyApp(ui = ui, server = server), port=9834)
```

In the UI call, the function that is called first corresponds to the plot that is displayed in the app.
Inspecting the elements, I see that the class element and visibility properties are changed when a plot is called second:

```
#cyjShiny first
<div id="igv-cyjShiny" style="width: 100%; height: 400px; visibility: inherit; -webkit-tap-highlight-color: rgba(0, 0, 0, 0);" class="cyjShiny html-widget html-widget-output shiny-bound-output __________cytoscape_container" aria-live="polite">…</div>
#igvShiny first
<div id="igv-cyjShiny" style="width:100%; height:400px; " class="cyjShiny html-widget html-widget-output"></div>
  
#igvShiny first
<div id="igv-igvShiny_0" class="igvShiny html-widget html-widget-output shiny-bound-output" aria-live="polite" style="visibility: inherit;">…</div>
#cyjShiny first
<div id="igv-igvShiny_0" class="igvShiny html-widget html-widget-output"></div>
```

Do you think this observation is helpful? I tried to change the div in the app UI call, but no change in behavior was observed, so maybe this needs to come from the library?.

**Comment by paul-shannon** [comment]
@heimannch - Hi Carol,
I think this is fixed now.  I had a ```const log``` function in both igvShiny.js and cyjShiny.js, unintentionally at global scope.    Whichever file loaded second choked on the  pre-existing```const``` definition of that function. 

```
cyjShiny version 1.0.35 on the master branch
igvShiny version 1.4.6 on the master branch
```

**Comment by heimannch** [comment]
Everything working fine now, thanks so much for the support!

**Comment by paul-shannon** [comment]
@heimannch Glad to hear this, Carol.  One of these days I'll do a proper job of learning ES6 and leave these scoping problems behind.
I have refactored the "local genomes" capability of igvShiny in a new branch.  I'd like to merge the work into master.   It will require only a very small adjustment to all client code, just a line or two.    

Would it fit your schedule for me to do that this afternoon?

**Comment by heimannch** [comment]
Of course, I am updating several app dependencies, so it's a great timing!
