### ISSUE TITLE
igvShiny 1.5.1 with new required argument to the constructor, genomeOptions

### ISSUE THREAD

**Issue by paul-shannon** [paul-shannon/igvShiny#29]
@heimannch @ChristianRohde @JAMKuttan

I merged the customGenomes branch into master, creating igvShiny version 1.5.1
The full details on specifying a custom genome can be seen in
```
inst/demos/customGenomes/customGenome-localFiles-sars.R
inst/demos/customGenomes/customGenome-remoteFiles-sars.R
```
When you use a stock genome - 35 are currently provided by the igv team -  here's what you do:

![image](https://user-images.githubusercontent.com/2480712/170805259-189b9726-4fc8-4a16-bff7-59495ac843f5.png)

then when you call the igvShiny constructor in your shiny server function, create a genome spec with almost all parameters taking default values:
```
     genomeOptions <- parseAndValidateGenomeSpec(genomeName="hg38",  initialLocus="NDUFS2")
     x <- igvShiny(genomeOptions,
                   displayMode="SQUISHED",
                   tracks=list()
                   )
```

**Comment by ChristianRohde** [comment]
Hi @paul-shannon I tested the new version 1.5.1 and after an update of the igvShiny() function it now works in my environment. Unfortunately, I see some problems with the loadBedGraphTrack function: after all it seems that now the track automatically gets removed. In my updated example which you find attached you can see this message:

[1] --- igvShiny.R loadBedGraphTrack, calling removeTracksByName: igvShiny_0, wig1b
[1] --- igvShiny sending message to js, removeTracksByName, wig1b

In my other productive Apps for data sharing I run into the same problem, but here I can zoom out/in and then I see the track. This is something I could not reproduce with my test App. Do you have any idea what could be the problem? 

Best,
Christian

[1.5.1_loadBedGraphTrack.zip](https://github.com/paul-shannon/igvShiny/files/8790859/1.5.1_loadBedGraphTrack.zip)

**Comment by paul-shannon** [comment]
@ChristianRohde    Here's a quick workaround - which I hope will suffice until I have time to dig deeper later this week.

- remove ```autoscaleGroup=1``` from both of your ```loadBedGraphTrack``` calls
- set ```autoscale=FALSE```
- calculate your own ```min``` and ```max```

It may well be that the ```autoscaleGroup``` capability is broken in my code, or less likely, in Jim Robinsons'.
I will track that down later this week.

Sorry for the trouble!

**Comment by heimannch** [comment]
Hi @paul-shannon. Thanks for the heads up and instructions! I updated my app and so far everything is working as expected.

**Comment by paul-shannon** [comment]
@ChristianRohde - creating a [new issue](https://github.com/paul-shannon/igvShiny/issues/30#issue-1261153265) for the autoscaleGroup bug.
