### ISSUE TITLE
Using IGV Shiny

### ISSUE THREAD

**Issue by millerh1** [paul-shannon/igvShiny#4]
This package is really interesting! I'm having a really tough time getting the widget to load and importing bed files to it. Would you mind giving a brief example of how to operate the package within a Shiny app?

Thank you!

**Comment by kikegoni** [comment]
Is it any update on this?

**Comment by paul-shannon** [comment]
@kikegoni @millerh1, I entirely missed this issue when Henry posted it a year ago. I apologize!

```inst/unitTests/igvShinyDemo.R```

 is a small but adequate example of using this widget within a shiny app.  

In that demo, the data.frame (bed "file") is created directly in the code, but base R's ```read.table``` function, called on a bed file, is easily substituted.

Give that a try, let me know if I can be of further help.

**Comment by paul-shannon** [comment]
apparently moribund - my fault for not tracking this when originally posted.
