### ISSUE TITLE
Your genome 'hg38' is not currently supported

### ISSUE THREAD

**Issue by ChristianRohde** [paul-shannon/igvShiny#43]
Hi,

I have not checked my Shiny-Scripts since a while. Today I see that I get an error with igvShiny when I try to load the genome:
genomeSpec <- parseAndValidateGenomeSpec("hg38", "APOE")
Error in parseAndValidateGenomeSpec("hg38", "APOE") : 
  Your genome 'hg38' is not currently supported
Currently supported: 

I am running igvShiny_1.5.1. Do you have an idea what could be wrong?

Best,
Christian

**Comment by ChristianRohde** [comment]
OK, sorry for asking too quick: after a re-install with remotes::install_github("paul-shannon/igvShiny", force=TRUE) I run now igvShiny_1.5.9005 and the error is gone.

Best,
Christian

**Comment by paul-shannon** [comment]
A thorough fix, including for all 30 genomes igv.js offers, is now in.   Version 1.5.9006.
Sorry for the trouble.
