### ISSUE TITLE
genome 'hg19' is not currently supported

### ISSUE THREAD

**Issue by heimannch** [paul-shannon/igvShiny#45]
Hi Paul,

My app is getting this error whenever igv is loading:

```
[1] --- leaving igvShiny.R, renderIgvShiny
Warning: Error in igvShiny::parseAndValidateGenomeSpec: Your genome 'hg19' is not currently supported
Currently supported: 
  99: stop
  98: igvShiny::parseAndValidateGenomeSpec
  97: ::
htmlwidgets
shinyRenderWidget [/Users/heimann/Documents/cri_iatlas/iatlas-app/R/germline_gwas_server.R#64]
```
It's important to us to use this genome version, as our app is mirroring a publication that used this assembly. Is there a reason to stop supporting this version?

Thanks!

**Comment by paul-shannon** [comment]
Hi Carol,

I think I fixed that a few weeks ago, in igvShiny and igvR.  The fix is in


  igvShiny/R/genomeSpec.R:

**Comment by paul-shannon** [comment]
This is igvShiny version 1.5.9009 from 2023-02-21

**Comment by paul-shannon** [comment]
here's the screenshot which failed:

![image](https://user-images.githubusercontent.com/2480712/225743077-71f05cb5-6d83-491f-87e2-2358f4efdf75.png)

**Comment by heimannch** [comment]
Thanks for the promptly reply - up and running again!
