### ISSUE TITLE
message.region

### ISSUE THREAD

**Issue by leipzig** [paul-shannon/igvShiny#6]
hi Paul,
This is a great widget!

I am wondering why you are using `message.region` here? For your demos I think you had it right with `message.roi`
https://github.com/paul-shannon/igvShiny/blob/cb876ac2b7822fb81f9b7ea3b061895ffa4b7fd4/inst/htmlwidgets/igvShiny.js#L188

**Comment by paul-shannon** [comment]
@leipzig  Forgive me for not responding.   I foolishly forgot to watch my own repo, so I did not see it until now.

Would an answer to your question still be of interest?

 - Paul

**Comment by leipzig** [comment]
nah I think I figured it out. keep up the good work!
